from pathlib import Path

path = Path('.github/scripts/f01-world-class-versioning.py')
text = path.read_text()
old = '''    anchor = f"\\t\\t\\tawait appendDomainEvidence(connection, {{\\n\\t\\t\\t\\tactor: input.actor,\\n\\t\\t\\t\\tactionKey: '{action}',"\n    prefix = f"\\t\\t\\tconst versionRow = await singleRow<RowDataPacket & {{ versionNumber: number | string; minorVersionNumber: number | string; snapshot: string | Record<string, unknown> }}>(`SELECT version_number AS versionNumber, minor_version_number AS minorVersionNumber, JSON_OBJECT({fields}) AS snapshot FROM {table} WHERE organisation_id = ? AND public_id = ? LIMIT 1`, [input.actor.organisationId, revisionPublicId]);\\n\\t\\t\\tawait appendGovernedVersion(connection, {{ actor: input.actor, domainCode: 'F01', recordType: '{record_type}', lineageKey: source.code, recordPublicId: revisionPublicId, versionNumber: Number(versionRow.versionNumber), minorVersionNumber: Number(versionRow.minorVersionNumber), lifecycleStatus: 'draft', snapshot: typeof versionRow.snapshot === 'string' ? JSON.parse(versionRow.snapshot) : versionRow.snapshot, changeNote: 'Controlled revision created from published version' }});\\n" + anchor\n'''
new = '''    indent = "\\t\\t" if action == "strategy.kpi.revise" else "\\t\\t\\t"\n    anchor = f"{indent}await appendDomainEvidence(connection, {{\\n{indent}\\tactor: input.actor,\\n{indent}\\tactionKey: '{action}',"\n    prefix = f"{indent}const versionRow = await singleRow<RowDataPacket & {{ versionNumber: number | string; minorVersionNumber: number | string; snapshot: string | Record<string, unknown> }}>(`SELECT version_number AS versionNumber, minor_version_number AS minorVersionNumber, JSON_OBJECT({fields}) AS snapshot FROM {table} WHERE organisation_id = ? AND public_id = ? LIMIT 1`, [input.actor.organisationId, revisionPublicId]);\\n{indent}await appendGovernedVersion(connection, {{ actor: input.actor, domainCode: 'F01', recordType: '{record_type}', lineageKey: source.code, recordPublicId: revisionPublicId, versionNumber: Number(versionRow.versionNumber), minorVersionNumber: Number(versionRow.minorVersionNumber), lifecycleStatus: 'draft', snapshot: typeof versionRow.snapshot === 'string' ? JSON.parse(versionRow.snapshot) : versionRow.snapshot, changeNote: 'Controlled revision created from published version' }});\\n" + anchor\n'''
if old not in text:
    raise SystemExit('Unable to patch revision snapshot indentation')
path.write_text(text.replace(old, new, 1))
