-- F05 Product, Service & Innovation Management — lifecycle control
-- F05.05 design, F05.06 development, F05.07 launch, F05.08 lifecycle, F05.09 retirement, F05.10 innovation experimentation.
-- migrate:up transaction:false

CREATE TABLE product_service_designs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    offering_id BIGINT UNSIGNED NOT NULL,
    business_case_id BIGINT UNSIGNED NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    design_code VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    design_brief TEXT NOT NULL,
    customer_outcomes TEXT NOT NULL,
    functional_requirements TEXT NOT NULL,
    non_functional_requirements TEXT NULL,
    acceptance_criteria TEXT NOT NULL,
    evidence_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    evidence_reference VARCHAR(500) NULL,
    lifecycle_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
    supersedes_design_id BIGINT UNSIGNED NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_design_public (organisation_id, public_id),
    UNIQUE KEY uq_product_service_design_version (organisation_id, offering_id, design_code, version_number),
    KEY ix_product_service_design_status (organisation_id, lifecycle_status),
    CONSTRAINT fk_product_service_design_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_design_offering FOREIGN KEY (offering_id) REFERENCES product_service_offerings(id),
    CONSTRAINT fk_product_service_design_business_case FOREIGN KEY (business_case_id) REFERENCES product_service_business_cases(id),
    CONSTRAINT fk_product_service_design_supersedes FOREIGN KEY (supersedes_design_id) REFERENCES product_service_designs(id),
    CONSTRAINT fk_product_service_design_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_design_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_design_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_design_version CHECK (version_number >= 1),
    CONSTRAINT chk_product_service_design_status CHECK (lifecycle_status IN ('draft', 'approved', 'superseded', 'withdrawn'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE product_service_design_reviews (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    design_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_code VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_type VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_date DATE NOT NULL,
    outcome VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    findings TEXT NOT NULL,
    actions_required TEXT NULL,
    evidence_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    reviewer_member_id BIGINT UNSIGNED NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_design_review_public (organisation_id, public_id),
    UNIQUE KEY uq_product_service_design_review_code (organisation_id, design_id, review_code),
    CONSTRAINT fk_product_service_design_review_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_design_review_design FOREIGN KEY (design_id) REFERENCES product_service_designs(id),
    CONSTRAINT fk_product_service_design_review_reviewer FOREIGN KEY (reviewer_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_design_review_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_design_review_type CHECK (review_type IN ('customer', 'technical', 'commercial', 'operational', 'compliance', 'sustainability', 'gate')),
    CONSTRAINT chk_product_service_design_review_outcome CHECK (outcome IN ('pass', 'conditional', 'fail'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE product_service_development_plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    offering_id BIGINT UNSIGNED NOT NULL,
    design_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    development_code VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    delivery_approach TEXT NOT NULL,
    scope_text TEXT NOT NULL,
    definition_of_done TEXT NOT NULL,
    planned_start DATE NULL,
    planned_finish DATE NULL,
    project_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    evidence_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    lifecycle_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'planned',
    owner_member_id BIGINT UNSIGNED NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    completed_by_member_id BIGINT UNSIGNED NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_development_public (organisation_id, public_id),
    UNIQUE KEY uq_product_service_development_code (organisation_id, development_code),
    CONSTRAINT fk_product_service_development_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_development_offering FOREIGN KEY (offering_id) REFERENCES product_service_offerings(id),
    CONSTRAINT fk_product_service_development_design FOREIGN KEY (design_id) REFERENCES product_service_designs(id),
    CONSTRAINT fk_product_service_development_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_development_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_development_completed_by FOREIGN KEY (completed_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_development_dates CHECK (planned_finish IS NULL OR planned_start IS NULL OR planned_finish >= planned_start),
    CONSTRAINT chk_product_service_development_status CHECK (lifecycle_status IN ('planned', 'in_progress', 'blocked', 'completed', 'cancelled'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE product_service_launch_plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    offering_id BIGINT UNSIGNED NOT NULL,
    development_plan_id BIGINT UNSIGNED NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    launch_code VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    target_launch_date DATE NOT NULL,
    target_segments TEXT NOT NULL,
    commercial_readiness TEXT NOT NULL,
    operational_readiness TEXT NOT NULL,
    customer_readiness TEXT NOT NULL,
    support_readiness TEXT NOT NULL,
    readiness_evidence_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    governance_decision_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    lifecycle_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'planning',
    owner_member_id BIGINT UNSIGNED NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at DATETIME(6) NULL,
    launched_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_launch_public (organisation_id, public_id),
    UNIQUE KEY uq_product_service_launch_code (organisation_id, launch_code),
    CONSTRAINT fk_product_service_launch_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_launch_offering FOREIGN KEY (offering_id) REFERENCES product_service_offerings(id),
    CONSTRAINT fk_product_service_launch_development FOREIGN KEY (development_plan_id) REFERENCES product_service_development_plans(id),
    CONSTRAINT fk_product_service_launch_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_launch_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_launch_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_launch_status CHECK (lifecycle_status IN ('planning', 'ready', 'approved', 'launched', 'cancelled'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE product_service_lifecycle_reviews (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    offering_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_code VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_date DATE NOT NULL,
    lifecycle_phase VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    performance_summary TEXT NOT NULL,
    customer_summary TEXT NOT NULL,
    financial_summary TEXT NOT NULL,
    risk_summary TEXT NOT NULL,
    recommendation VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    performance_evidence_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    customer_evidence_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_lifecycle_review_public (organisation_id, public_id),
    UNIQUE KEY uq_product_service_lifecycle_review_code (organisation_id, offering_id, review_code),
    CONSTRAINT fk_product_service_lifecycle_review_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_lifecycle_review_offering FOREIGN KEY (offering_id) REFERENCES product_service_offerings(id),
    CONSTRAINT fk_product_service_lifecycle_review_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_lifecycle_review_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_lifecycle_phase CHECK (lifecycle_phase IN ('launch', 'growth', 'maturity', 'decline', 'end_of_life')),
    CONSTRAINT chk_product_service_lifecycle_recommendation CHECK (recommendation IN ('continue', 'improve', 'reposition', 'invest', 'retire'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE product_service_retirement_plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    offering_id BIGINT UNSIGNED NOT NULL,
    lifecycle_review_id BIGINT UNSIGNED NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    retirement_code VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    retirement_rationale TEXT NOT NULL,
    customer_transition_plan TEXT NOT NULL,
    operational_transition_plan TEXT NOT NULL,
    financial_impact_summary TEXT NOT NULL,
    data_record_retention_plan TEXT NOT NULL,
    target_end_date DATE NOT NULL,
    governance_decision_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    lifecycle_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
    owner_member_id BIGINT UNSIGNED NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_retirement_public (organisation_id, public_id),
    UNIQUE KEY uq_product_service_retirement_code (organisation_id, retirement_code),
    CONSTRAINT fk_product_service_retirement_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_retirement_offering FOREIGN KEY (offering_id) REFERENCES product_service_offerings(id),
    CONSTRAINT fk_product_service_retirement_review FOREIGN KEY (lifecycle_review_id) REFERENCES product_service_lifecycle_reviews(id),
    CONSTRAINT fk_product_service_retirement_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_retirement_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_retirement_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_retirement_status CHECK (lifecycle_status IN ('draft', 'approved', 'in_progress', 'completed', 'cancelled'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE product_service_innovation_experiments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    portfolio_id BIGINT UNSIGNED NULL,
    idea_id BIGINT UNSIGNED NULL,
    offering_id BIGINT UNSIGNED NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    experiment_code VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    hypothesis TEXT NOT NULL,
    experiment_method TEXT NOT NULL,
    success_measure TEXT NOT NULL,
    planned_start DATE NULL,
    planned_finish DATE NULL,
    lifecycle_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'planned',
    outcome VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
    learning_summary TEXT NULL,
    evidence_public_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    closed_by_member_id BIGINT UNSIGNED NULL,
    closed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_experiment_public (organisation_id, public_id),
    UNIQUE KEY uq_product_service_experiment_code (organisation_id, experiment_code),
    CONSTRAINT fk_product_service_experiment_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_experiment_portfolio FOREIGN KEY (portfolio_id) REFERENCES product_service_portfolios(id),
    CONSTRAINT fk_product_service_experiment_idea FOREIGN KEY (idea_id) REFERENCES product_service_ideas(id),
    CONSTRAINT fk_product_service_experiment_offering FOREIGN KEY (offering_id) REFERENCES product_service_offerings(id),
    CONSTRAINT fk_product_service_experiment_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_experiment_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_experiment_closed_by FOREIGN KEY (closed_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_experiment_dates CHECK (planned_finish IS NULL OR planned_start IS NULL OR planned_finish >= planned_start),
    CONSTRAINT chk_product_service_experiment_status CHECK (lifecycle_status IN ('planned', 'running', 'completed', 'cancelled')),
    CONSTRAINT chk_product_service_experiment_outcome CHECK (outcome IS NULL OR outcome IN ('validated', 'invalidated', 'inconclusive'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- migrate:down
SELECT 1;
