-- migrate:up

CREATE TABLE corporate_development_opportunities (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    opportunity_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    deal_type VARCHAR(30) NOT NULL,
    target_name VARCHAR(255) NOT NULL,
    target_source_domain VARCHAR(50) NULL,
    target_source_record_type VARCHAR(80) NULL,
    target_source_public_id VARCHAR(100) NULL,
    strategic_thesis TEXT NOT NULL,
    strategic_rationale TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'medium',
    pipeline_stage VARCHAR(30) NOT NULL DEFAULT 'identified',
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'active',
    identified_on DATE NOT NULL,
    target_decision_date DATE NULL,
    strategy_objective_public_id VARCHAR(100) NULL,
    strategy_kpi_public_id VARCHAR(100) NULL,
    performance_evidence_public_id VARCHAR(100) NULL,
    source_reference VARCHAR(500) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_opportunity_public (public_id),
    UNIQUE KEY uq_corpdev_opportunity_code (organisation_id, opportunity_code),
    KEY idx_corpdev_opportunity_pipeline (organisation_id, pipeline_stage, lifecycle_status),
    CONSTRAINT fk_corpdev_opportunity_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_opportunity_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_opportunity_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_opportunity_deal_type CHECK (deal_type IN ('acquisition','divestiture','joint_venture','strategic_partnership','minority_investment','other')),
    CONSTRAINT chk_corpdev_opportunity_priority CHECK (priority IN ('low','medium','high','critical')),
    CONSTRAINT chk_corpdev_opportunity_stage CHECK (pipeline_stage IN ('identified','screening','valuation','diligence','negotiation','approval','signed','closed','integration','on_hold','declined','withdrawn')),
    CONSTRAINT chk_corpdev_opportunity_status CHECK (lifecycle_status IN ('active','on_hold','completed','cancelled'))
);

CREATE TABLE corporate_development_opportunity_stage_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    opportunity_id BIGINT UNSIGNED NOT NULL,
    from_stage VARCHAR(30) NULL,
    to_stage VARCHAR(30) NOT NULL,
    transition_reason TEXT NOT NULL,
    transitioned_by_member_id BIGINT UNSIGNED NOT NULL,
    transitioned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_stage_history_public (public_id),
    KEY idx_corpdev_stage_history_opportunity (organisation_id, opportunity_id, transitioned_at),
    CONSTRAINT fk_corpdev_stage_history_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_stage_history_opportunity FOREIGN KEY (opportunity_id) REFERENCES corporate_development_opportunities(id),
    CONSTRAINT fk_corpdev_stage_history_member FOREIGN KEY (transitioned_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_stage_history_to CHECK (to_stage IN ('identified','screening','valuation','diligence','negotiation','approval','signed','closed','integration','on_hold','declined','withdrawn'))
);

CREATE TABLE corporate_development_valuations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    opportunity_id BIGINT UNSIGNED NOT NULL,
    valuation_code VARCHAR(50) NOT NULL,
    version_number INT UNSIGNED NOT NULL DEFAULT 1,
    title VARCHAR(255) NOT NULL,
    valuation_date DATE NOT NULL,
    currency_code CHAR(3) NOT NULL,
    primary_method VARCHAR(30) NOT NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'draft',
    enterprise_value_low DECIMAL(20,4) NULL,
    enterprise_value_base DECIMAL(20,4) NULL,
    enterprise_value_high DECIMAL(20,4) NULL,
    equity_value_low DECIMAL(20,4) NULL,
    equity_value_base DECIMAL(20,4) NULL,
    equity_value_high DECIMAL(20,4) NULL,
    recommendation TEXT NOT NULL,
    supersedes_valuation_id BIGINT UNSIGNED NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at TIMESTAMP NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_valuation_public (public_id),
    UNIQUE KEY uq_corpdev_valuation_version (organisation_id, opportunity_id, valuation_code, version_number),
    KEY idx_corpdev_valuation_opportunity (organisation_id, opportunity_id, lifecycle_status),
    CONSTRAINT fk_corpdev_valuation_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_valuation_opportunity FOREIGN KEY (opportunity_id) REFERENCES corporate_development_opportunities(id),
    CONSTRAINT fk_corpdev_valuation_supersedes FOREIGN KEY (supersedes_valuation_id) REFERENCES corporate_development_valuations(id),
    CONSTRAINT fk_corpdev_valuation_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_valuation_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_valuation_method CHECK (primary_method IN ('dcf','precedent_transactions','trading_comparables','asset_based','sum_of_parts','venture_method','other')),
    CONSTRAINT chk_corpdev_valuation_status CHECK (lifecycle_status IN ('draft','approved','superseded','withdrawn')),
    CONSTRAINT chk_corpdev_valuation_ev_range CHECK (enterprise_value_low IS NULL OR enterprise_value_high IS NULL OR enterprise_value_low <= enterprise_value_high),
    CONSTRAINT chk_corpdev_valuation_equity_range CHECK (equity_value_low IS NULL OR equity_value_high IS NULL OR equity_value_low <= equity_value_high)
);

CREATE TABLE corporate_development_valuation_scenarios (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    valuation_id BIGINT UNSIGNED NOT NULL,
    scenario_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    scenario_type VARCHAR(20) NOT NULL,
    probability_percent DECIMAL(7,4) NULL,
    enterprise_value DECIMAL(20,4) NULL,
    equity_value DECIMAL(20,4) NULL,
    consideration_value DECIMAL(20,4) NULL,
    synergy_value DECIMAL(20,4) NULL,
    narrative TEXT NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_valuation_scenario_public (public_id),
    UNIQUE KEY uq_corpdev_valuation_scenario_code (organisation_id, valuation_id, scenario_code),
    CONSTRAINT fk_corpdev_valuation_scenario_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_valuation_scenario_valuation FOREIGN KEY (valuation_id) REFERENCES corporate_development_valuations(id),
    CONSTRAINT fk_corpdev_valuation_scenario_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_valuation_scenario_type CHECK (scenario_type IN ('downside','base','upside','stress','custom')),
    CONSTRAINT chk_corpdev_valuation_scenario_probability CHECK (probability_percent IS NULL OR (probability_percent >= 0 AND probability_percent <= 100))
);

CREATE TABLE corporate_development_valuation_assumptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    valuation_scenario_id BIGINT UNSIGNED NOT NULL,
    assumption_code VARCHAR(80) NOT NULL,
    title VARCHAR(255) NOT NULL,
    assumption_type VARCHAR(30) NOT NULL,
    numeric_value DECIMAL(24,8) NULL,
    text_value TEXT NULL,
    unit_label VARCHAR(50) NULL,
    source_domain VARCHAR(50) NULL,
    source_record_type VARCHAR(80) NULL,
    source_public_id VARCHAR(100) NULL,
    source_reference VARCHAR(500) NULL,
    confidence_percent DECIMAL(7,4) NULL,
    rationale TEXT NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_valuation_assumption_public (public_id),
    UNIQUE KEY uq_corpdev_valuation_assumption_code (organisation_id, valuation_scenario_id, assumption_code),
    CONSTRAINT fk_corpdev_valuation_assumption_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_valuation_assumption_scenario FOREIGN KEY (valuation_scenario_id) REFERENCES corporate_development_valuation_scenarios(id),
    CONSTRAINT fk_corpdev_valuation_assumption_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_valuation_assumption_type CHECK (assumption_type IN ('revenue','growth','margin','discount_rate','terminal_growth','multiple','net_debt','cash','synergy','tax','capex','working_capital','other')),
    CONSTRAINT chk_corpdev_valuation_assumption_confidence CHECK (confidence_percent IS NULL OR (confidence_percent >= 0 AND confidence_percent <= 100)),
    CONSTRAINT chk_corpdev_valuation_assumption_value CHECK (numeric_value IS NOT NULL OR text_value IS NOT NULL)
);

-- migrate:down
DROP TABLE IF EXISTS corporate_development_valuation_assumptions;
DROP TABLE IF EXISTS corporate_development_valuation_scenarios;
DROP TABLE IF EXISTS corporate_development_valuations;
DROP TABLE IF EXISTS corporate_development_opportunity_stage_history;
DROP TABLE IF EXISTS corporate_development_opportunities;