-- migrate:up

CREATE TABLE product_service_portfolios (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    portfolio_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    portfolio_type VARCHAR(30) NOT NULL,
    strategic_thesis TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'medium',
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'active',
    strategy_objective_public_id VARCHAR(100) NULL,
    strategy_kpi_public_id VARCHAR(100) NULL,
    performance_evidence_public_id VARCHAR(100) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_portfolio_public (public_id),
    UNIQUE KEY uq_product_service_portfolio_code (organisation_id, portfolio_code),
    KEY idx_product_service_portfolio_status (organisation_id, lifecycle_status, priority),
    CONSTRAINT fk_product_service_portfolio_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_portfolio_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_portfolio_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_portfolio_type CHECK (portfolio_type IN ('product','service','mixed','platform','innovation')),
    CONSTRAINT chk_product_service_portfolio_priority CHECK (priority IN ('low','medium','high','critical')),
    CONSTRAINT chk_product_service_portfolio_status CHECK (lifecycle_status IN ('draft','active','on_hold','retired','cancelled'))
);

CREATE TABLE product_service_offerings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    portfolio_id BIGINT UNSIGNED NOT NULL,
    offering_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    offering_type VARCHAR(30) NOT NULL,
    value_proposition TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    lifecycle_stage VARCHAR(30) NOT NULL DEFAULT 'concept',
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'active',
    current_version VARCHAR(50) NULL,
    launched_on DATE NULL,
    target_retirement_on DATE NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_offering_public (public_id),
    UNIQUE KEY uq_product_service_offering_code (organisation_id, offering_code),
    KEY idx_product_service_offering_lifecycle (organisation_id, portfolio_id, lifecycle_stage, lifecycle_status),
    CONSTRAINT fk_product_service_offering_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_offering_portfolio FOREIGN KEY (portfolio_id) REFERENCES product_service_portfolios(id),
    CONSTRAINT fk_product_service_offering_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_offering_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_offering_type CHECK (offering_type IN ('product','service','platform','solution','internal_capability','other')),
    CONSTRAINT chk_product_service_offering_stage CHECK (lifecycle_stage IN ('concept','discovery','business_case','design','development','launch','live','mature','retirement','retired')),
    CONSTRAINT chk_product_service_offering_status CHECK (lifecycle_status IN ('active','on_hold','retired','cancelled'))
);

CREATE TABLE product_service_needs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    portfolio_id BIGINT UNSIGNED NULL,
    need_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    need_type VARCHAR(30) NOT NULL,
    need_statement TEXT NOT NULL,
    source_domain VARCHAR(50) NOT NULL,
    source_record_type VARCHAR(80) NULL,
    source_public_id VARCHAR(100) NULL,
    source_reference VARCHAR(500) NULL,
    customer_or_market_segment VARCHAR(255) NULL,
    evidence_strength VARCHAR(20) NOT NULL DEFAULT 'medium',
    urgency VARCHAR(20) NOT NULL DEFAULT 'medium',
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    owner_member_id BIGINT UNSIGNED NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_need_public (public_id),
    UNIQUE KEY uq_product_service_need_code (organisation_id, need_code),
    KEY idx_product_service_need_status (organisation_id, status, urgency),
    CONSTRAINT fk_product_service_need_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_need_portfolio FOREIGN KEY (portfolio_id) REFERENCES product_service_portfolios(id),
    CONSTRAINT fk_product_service_need_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_need_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_need_type CHECK (need_type IN ('customer','market','operational','regulatory','technology','sustainability','commercial','other')),
    CONSTRAINT chk_product_service_need_evidence CHECK (evidence_strength IN ('low','medium','high','validated')),
    CONSTRAINT chk_product_service_need_urgency CHECK (urgency IN ('low','medium','high','critical')),
    CONSTRAINT chk_product_service_need_status CHECK (status IN ('open','validated','addressed','rejected','superseded'))
);

CREATE TABLE product_service_ideas (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    portfolio_id BIGINT UNSIGNED NULL,
    need_id BIGINT UNSIGNED NULL,
    idea_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    idea_type VARCHAR(30) NOT NULL,
    problem_statement TEXT NOT NULL,
    proposed_value TEXT NOT NULL,
    provenance VARCHAR(50) NOT NULL,
    source_reference VARCHAR(500) NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    stage VARCHAR(30) NOT NULL DEFAULT 'submitted',
    strategic_fit_score DECIMAL(7,4) NULL,
    customer_value_score DECIMAL(7,4) NULL,
    feasibility_score DECIMAL(7,4) NULL,
    commercial_value_score DECIMAL(7,4) NULL,
    risk_score DECIMAL(7,4) NULL,
    overall_score DECIMAL(7,4) NULL,
    duplicate_of_idea_id BIGINT UNSIGNED NULL,
    decision_reason TEXT NULL,
    decided_by_member_id BIGINT UNSIGNED NULL,
    decided_at TIMESTAMP NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_idea_public (public_id),
    UNIQUE KEY uq_product_service_idea_code (organisation_id, idea_code),
    KEY idx_product_service_idea_funnel (organisation_id, stage, overall_score),
    CONSTRAINT fk_product_service_idea_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_idea_portfolio FOREIGN KEY (portfolio_id) REFERENCES product_service_portfolios(id),
    CONSTRAINT fk_product_service_idea_need FOREIGN KEY (need_id) REFERENCES product_service_needs(id),
    CONSTRAINT fk_product_service_idea_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_idea_duplicate FOREIGN KEY (duplicate_of_idea_id) REFERENCES product_service_ideas(id),
    CONSTRAINT fk_product_service_idea_decided_by FOREIGN KEY (decided_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_idea_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_idea_type CHECK (idea_type IN ('new_product','new_service','enhancement','process_innovation','technology_innovation','business_model','other')),
    CONSTRAINT chk_product_service_idea_stage CHECK (stage IN ('submitted','triage','discovery','business_case','approved','rejected','parked','converted')),
    CONSTRAINT chk_product_service_idea_scores CHECK ((strategic_fit_score IS NULL OR strategic_fit_score BETWEEN 0 AND 100) AND (customer_value_score IS NULL OR customer_value_score BETWEEN 0 AND 100) AND (feasibility_score IS NULL OR feasibility_score BETWEEN 0 AND 100) AND (commercial_value_score IS NULL OR commercial_value_score BETWEEN 0 AND 100) AND (risk_score IS NULL OR risk_score BETWEEN 0 AND 100) AND (overall_score IS NULL OR overall_score BETWEEN 0 AND 100))
);

CREATE TABLE product_service_business_cases (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    idea_id BIGINT UNSIGNED NOT NULL,
    offering_id BIGINT UNSIGNED NULL,
    business_case_code VARCHAR(50) NOT NULL,
    version_number INT UNSIGNED NOT NULL DEFAULT 1,
    title VARCHAR(255) NOT NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'draft',
    currency_code CHAR(3) NOT NULL,
    investment_cost DECIMAL(20,4) NULL,
    annual_operating_cost DECIMAL(20,4) NULL,
    annual_revenue_or_value DECIMAL(20,4) NULL,
    expected_benefit_value DECIMAL(20,4) NULL,
    payback_months INT UNSIGNED NULL,
    risk_summary TEXT NOT NULL,
    recommendation TEXT NOT NULL,
    strategy_objective_public_id VARCHAR(100) NULL,
    performance_benefit_public_id VARCHAR(100) NULL,
    supersedes_business_case_id BIGINT UNSIGNED NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at TIMESTAMP NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_business_case_public (public_id),
    UNIQUE KEY uq_product_service_business_case_version (organisation_id, idea_id, business_case_code, version_number),
    KEY idx_product_service_business_case_status (organisation_id, idea_id, lifecycle_status),
    CONSTRAINT fk_product_service_business_case_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_business_case_idea FOREIGN KEY (idea_id) REFERENCES product_service_ideas(id),
    CONSTRAINT fk_product_service_business_case_offering FOREIGN KEY (offering_id) REFERENCES product_service_offerings(id),
    CONSTRAINT fk_product_service_business_case_supersedes FOREIGN KEY (supersedes_business_case_id) REFERENCES product_service_business_cases(id),
    CONSTRAINT fk_product_service_business_case_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_product_service_business_case_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_business_case_status CHECK (lifecycle_status IN ('draft','submitted','approved','rejected','superseded','withdrawn'))
);

CREATE TABLE product_service_business_case_assumptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    business_case_id BIGINT UNSIGNED NOT NULL,
    assumption_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    assumption_type VARCHAR(30) NOT NULL,
    numeric_value DECIMAL(24,8) NULL,
    text_value TEXT NULL,
    unit_label VARCHAR(50) NULL,
    source_domain VARCHAR(50) NULL,
    source_record_type VARCHAR(80) NULL,
    source_public_id VARCHAR(100) NULL,
    source_reference VARCHAR(500) NULL,
    confidence_percent DECIMAL(7,4) NULL,
    rationale TEXT NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_bc_assumption_public (public_id),
    UNIQUE KEY uq_product_service_bc_assumption_code (organisation_id, business_case_id, assumption_code),
    CONSTRAINT fk_product_service_bc_assumption_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_bc_assumption_case FOREIGN KEY (business_case_id) REFERENCES product_service_business_cases(id),
    CONSTRAINT fk_product_service_bc_assumption_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_bc_assumption_type CHECK (assumption_type IN ('cost','revenue','benefit','volume','price','adoption','capacity','schedule','risk','other')),
    CONSTRAINT chk_product_service_bc_assumption_confidence CHECK (confidence_percent IS NULL OR confidence_percent BETWEEN 0 AND 100),
    CONSTRAINT chk_product_service_bc_assumption_value CHECK (numeric_value IS NOT NULL OR text_value IS NOT NULL)
);

CREATE TABLE product_service_business_case_scenarios (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    business_case_id BIGINT UNSIGNED NOT NULL,
    scenario_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    scenario_type VARCHAR(20) NOT NULL,
    probability_percent DECIMAL(7,4) NULL,
    investment_cost DECIMAL(20,4) NULL,
    annual_revenue_or_value DECIMAL(20,4) NULL,
    expected_benefit_value DECIMAL(20,4) NULL,
    narrative TEXT NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_service_bc_scenario_public (public_id),
    UNIQUE KEY uq_product_service_bc_scenario_code (organisation_id, business_case_id, scenario_code),
    CONSTRAINT fk_product_service_bc_scenario_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_product_service_bc_scenario_case FOREIGN KEY (business_case_id) REFERENCES product_service_business_cases(id),
    CONSTRAINT fk_product_service_bc_scenario_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_product_service_bc_scenario_type CHECK (scenario_type IN ('downside','base','upside','stress','custom')),
    CONSTRAINT chk_product_service_bc_scenario_probability CHECK (probability_percent IS NULL OR probability_percent BETWEEN 0 AND 100)
);

-- migrate:down
SELECT 1;
