-- F01 Strategy & Enterprise Planning — Tranche C
-- Goal/KPI management, strategic review, scenario and foresight planning.
-- migrate:up transaction:false

CREATE TABLE strategy_kpis (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_framework_id BIGINT UNSIGNED NOT NULL,
    strategy_objective_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    kpi_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    unit_label VARCHAR(64) NOT NULL,
    direction VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    aggregation_method VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'latest',
    baseline_value DECIMAL(24,8) NOT NULL,
    target_value DECIMAL(24,8) NOT NULL,
    warning_threshold DECIMAL(24,8) NULL,
    critical_threshold DECIMAL(24,8) NULL,
    target_date DATE NULL,
    source_mode VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'manual',
    source_domain VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_record_type VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_measure_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
    supersedes_strategy_kpi_id BIGINT UNSIGNED NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_kpi_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_kpi_version (organisation_id, kpi_code, version_number),
    KEY ix_strategy_kpi_objective (strategy_objective_id, lifecycle_status, kpi_code),
    KEY ix_strategy_kpi_framework (strategy_framework_id, lifecycle_status),
    CONSTRAINT fk_strategy_kpi_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_kpi_framework FOREIGN KEY (strategy_framework_id) REFERENCES strategy_frameworks(id),
    CONSTRAINT fk_strategy_kpi_objective FOREIGN KEY (strategy_objective_id) REFERENCES strategy_objectives(id),
    CONSTRAINT fk_strategy_kpi_supersedes FOREIGN KEY (supersedes_strategy_kpi_id) REFERENCES strategy_kpis(id),
    CONSTRAINT fk_strategy_kpi_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_kpi_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_kpi_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_kpi_version CHECK (version_number >= 1),
    CONSTRAINT chk_strategy_kpi_direction CHECK (direction IN ('higher_is_better', 'lower_is_better', 'target_is_best', 'band')),
    CONSTRAINT chk_strategy_kpi_aggregation CHECK (aggregation_method IN ('latest', 'sum', 'average', 'minimum', 'maximum', 'ratio')),
    CONSTRAINT chk_strategy_kpi_source_mode CHECK (source_mode IN ('manual', 'canonical')),
    CONSTRAINT chk_strategy_kpi_status CHECK (lifecycle_status IN ('draft', 'approved', 'superseded', 'retired')),
    CONSTRAINT chk_strategy_kpi_source_evidence CHECK (source_mode = 'manual' OR (source_domain IS NOT NULL AND source_record_type IS NOT NULL AND source_measure_key IS NOT NULL))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_kpi_observations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    observed_on DATE NOT NULL,
    actual_value DECIMAL(24,8) NOT NULL,
    forecast_value DECIMAL(24,8) NULL,
    commentary TEXT NULL,
    source_mode VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'manual',
    source_domain VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_record_type VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_public_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_measure_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_kpi_observation_public (organisation_id, public_id),
    KEY ix_strategy_kpi_observation_date (strategy_kpi_id, observed_on, created_at),
    CONSTRAINT fk_strategy_kpi_observation_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_kpi_observation_kpi FOREIGN KEY (strategy_kpi_id) REFERENCES strategy_kpis(id),
    CONSTRAINT fk_strategy_kpi_observation_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_kpi_observation_source_mode CHECK (source_mode IN ('manual', 'canonical')),
    CONSTRAINT chk_strategy_kpi_observation_source_evidence CHECK (source_mode = 'manual' OR (source_domain IS NOT NULL AND source_record_type IS NOT NULL AND source_public_id IS NOT NULL AND source_measure_key IS NOT NULL))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_kpi_actions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_observation_id BIGINT UNSIGNED NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    action_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    action_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    due_date DATE NOT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'open',
    completion_note TEXT NULL,
    completed_at DATETIME(6) NULL,
    completed_by_member_id BIGINT UNSIGNED NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_kpi_action_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_kpi_action_code (strategy_kpi_id, action_code),
    KEY ix_strategy_kpi_action_status (strategy_kpi_id, lifecycle_status, due_date),
    CONSTRAINT fk_strategy_kpi_action_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_kpi_action_kpi FOREIGN KEY (strategy_kpi_id) REFERENCES strategy_kpis(id),
    CONSTRAINT fk_strategy_kpi_action_observation FOREIGN KEY (strategy_kpi_observation_id) REFERENCES strategy_kpi_observations(id),
    CONSTRAINT fk_strategy_kpi_action_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_kpi_action_completed_by FOREIGN KEY (completed_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_kpi_action_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_kpi_action_status CHECK (lifecycle_status IN ('open', 'in_progress', 'completed', 'cancelled')),
    CONSTRAINT chk_strategy_kpi_action_completion CHECK (lifecycle_status <> 'completed' OR (completed_at IS NOT NULL AND completed_by_member_id IS NOT NULL))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_reviews (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_framework_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    decisions_text TEXT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_review_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_review_code (strategy_framework_id, review_code),
    KEY ix_strategy_review_date (strategy_framework_id, review_date, lifecycle_status),
    CONSTRAINT fk_strategy_review_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_review_framework FOREIGN KEY (strategy_framework_id) REFERENCES strategy_frameworks(id),
    CONSTRAINT fk_strategy_review_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_review_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_review_status CHECK (lifecycle_status IN ('draft', 'approved'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_review_kpis (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_review_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_observation_id BIGINT UNSIGNED NOT NULL,
    actual_value_snapshot DECIMAL(24,8) NOT NULL,
    target_value_snapshot DECIMAL(24,8) NOT NULL,
    variance_value DECIMAL(24,8) NOT NULL,
    variance_percent DECIMAL(18,8) NULL,
    assessment VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    commentary TEXT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_review_kpi (strategy_review_id, strategy_kpi_id),
    KEY ix_strategy_review_kpi_assessment (strategy_review_id, assessment),
    CONSTRAINT fk_strategy_review_kpi_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_review_kpi_review FOREIGN KEY (strategy_review_id) REFERENCES strategy_reviews(id),
    CONSTRAINT fk_strategy_review_kpi_kpi FOREIGN KEY (strategy_kpi_id) REFERENCES strategy_kpis(id),
    CONSTRAINT fk_strategy_review_kpi_observation FOREIGN KEY (strategy_kpi_observation_id) REFERENCES strategy_kpi_observations(id),
    CONSTRAINT fk_strategy_review_kpi_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_review_kpi_assessment CHECK (assessment IN ('on_track', 'watch', 'off_track', 'not_measured'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_scenarios (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_framework_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    scenario_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    scenario_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    horizon_start DATE NOT NULL,
    horizon_end DATE NOT NULL,
    narrative TEXT NOT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
    supersedes_strategy_scenario_id BIGINT UNSIGNED NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_scenario_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_scenario_version (organisation_id, scenario_code, version_number),
    KEY ix_strategy_scenario_framework (strategy_framework_id, lifecycle_status, scenario_type),
    CONSTRAINT fk_strategy_scenario_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_scenario_framework FOREIGN KEY (strategy_framework_id) REFERENCES strategy_frameworks(id),
    CONSTRAINT fk_strategy_scenario_supersedes FOREIGN KEY (supersedes_strategy_scenario_id) REFERENCES strategy_scenarios(id),
    CONSTRAINT fk_strategy_scenario_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_scenario_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_scenario_version CHECK (version_number >= 1),
    CONSTRAINT chk_strategy_scenario_horizon CHECK (horizon_end >= horizon_start),
    CONSTRAINT chk_strategy_scenario_type CHECK (scenario_type IN ('baseline', 'upside', 'downside', 'stress', 'custom')),
    CONSTRAINT chk_strategy_scenario_status CHECK (lifecycle_status IN ('draft', 'approved', 'superseded'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_scenario_assumptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_scenario_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    assumption_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    variable_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    unit_label VARCHAR(64) NOT NULL,
    baseline_value DECIMAL(24,8) NOT NULL,
    scenario_value DECIMAL(24,8) NOT NULL,
    sensitivity_percent DECIMAL(12,6) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_scenario_assumption_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_scenario_assumption_code (strategy_scenario_id, assumption_code),
    CONSTRAINT fk_strategy_scenario_assumption_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_scenario_assumption_scenario FOREIGN KEY (strategy_scenario_id) REFERENCES strategy_scenarios(id),
    CONSTRAINT fk_strategy_scenario_assumption_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_scenario_assumption_sensitivity CHECK (sensitivity_percent IS NULL OR sensitivity_percent >= 0)
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_scenario_kpi_projections (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_scenario_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    projection_date DATE NOT NULL,
    projected_value DECIMAL(24,8) NOT NULL,
    rationale TEXT NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_scenario_projection_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_scenario_projection (strategy_scenario_id, strategy_kpi_id, projection_date),
    KEY ix_strategy_scenario_projection_kpi (strategy_kpi_id, projection_date),
    CONSTRAINT fk_strategy_scenario_projection_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_scenario_projection_scenario FOREIGN KEY (strategy_scenario_id) REFERENCES strategy_scenarios(id),
    CONSTRAINT fk_strategy_scenario_projection_kpi FOREIGN KEY (strategy_kpi_id) REFERENCES strategy_kpis(id),
    CONSTRAINT fk_strategy_scenario_projection_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id)
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- migrate:down transaction:false
-- Approved KPI, review and scenario evidence is forward-only enterprise evidence.
-- Non-production environments are rebuilt from the authoritative migration stream.
SELECT 1;
