-- F03 Enterprise Performance Management
-- Performance framework, reporting, variance/action, management review, benchmarking and benefits realisation.
-- Canonical F01 KPI definitions/targets/observations remain authoritative and are referenced, not duplicated.
-- migrate:up transaction:false

CREATE TABLE strategy_performance_frameworks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    framework_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    purpose_text TEXT NOT NULL,
    reporting_cadence VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    scope_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    supersedes_performance_framework_id BIGINT UNSIGNED NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_framework_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_framework_version (organisation_id, framework_code, version_number),
    KEY ix_strategy_performance_framework_status (organisation_id, lifecycle_status, effective_from),
    CONSTRAINT fk_strategy_performance_framework_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_framework_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_framework_supersedes FOREIGN KEY (supersedes_performance_framework_id) REFERENCES strategy_performance_frameworks(id),
    CONSTRAINT fk_strategy_performance_framework_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_framework_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_framework_version CHECK (version_number >= 1),
    CONSTRAINT chk_strategy_performance_framework_cadence CHECK (reporting_cadence IN ('weekly','monthly','quarterly','annual')),
    CONSTRAINT chk_strategy_performance_framework_status CHECK (lifecycle_status IN ('draft','approved','superseded','retired')),
    CONSTRAINT chk_strategy_performance_framework_dates CHECK (effective_to IS NULL OR effective_to >= effective_from)
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_framework_kpis (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    performance_framework_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_id BIGINT UNSIGNED NOT NULL,
    display_order INT UNSIGNED NOT NULL DEFAULT 1,
    materiality_threshold_percent DECIMAL(12,6) NULL,
    commentary_required BOOLEAN NOT NULL DEFAULT FALSE,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_framework_kpi (performance_framework_id, strategy_kpi_id),
    KEY ix_strategy_performance_framework_kpi_order (performance_framework_id, display_order),
    CONSTRAINT fk_strategy_performance_framework_kpi_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_framework_kpi_framework FOREIGN KEY (performance_framework_id) REFERENCES strategy_performance_frameworks(id),
    CONSTRAINT fk_strategy_performance_framework_kpi_kpi FOREIGN KEY (strategy_kpi_id) REFERENCES strategy_kpis(id),
    CONSTRAINT fk_strategy_performance_framework_kpi_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_framework_kpi_threshold CHECK (materiality_threshold_percent IS NULL OR materiality_threshold_percent >= 0)
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_periods (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    performance_framework_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    period_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    reporting_date DATE NOT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'open',
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    closed_by_member_id BIGINT UNSIGNED NULL,
    closed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_period_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_period_code (performance_framework_id, period_code),
    KEY ix_strategy_performance_period_dates (performance_framework_id, period_end, lifecycle_status),
    CONSTRAINT fk_strategy_performance_period_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_period_framework FOREIGN KEY (performance_framework_id) REFERENCES strategy_performance_frameworks(id),
    CONSTRAINT fk_strategy_performance_period_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_period_closed_by FOREIGN KEY (closed_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_period_dates CHECK (period_end >= period_start AND reporting_date >= period_end),
    CONSTRAINT chk_strategy_performance_period_status CHECK (lifecycle_status IN ('open','reported','closed')),
    CONSTRAINT chk_strategy_performance_period_closed CHECK (lifecycle_status <> 'closed' OR (closed_by_member_id IS NOT NULL AND closed_at IS NOT NULL))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_packs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    performance_period_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    pack_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    version_number INT UNSIGNED NOT NULL DEFAULT 1,
    title VARCHAR(255) NOT NULL,
    executive_summary TEXT NOT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
    supersedes_performance_pack_id BIGINT UNSIGNED NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_pack_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_pack_version (performance_period_id, pack_code, version_number),
    KEY ix_strategy_performance_pack_status (performance_period_id, lifecycle_status, version_number),
    CONSTRAINT fk_strategy_performance_pack_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_pack_period FOREIGN KEY (performance_period_id) REFERENCES strategy_performance_periods(id),
    CONSTRAINT fk_strategy_performance_pack_supersedes FOREIGN KEY (supersedes_performance_pack_id) REFERENCES strategy_performance_packs(id),
    CONSTRAINT fk_strategy_performance_pack_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_pack_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_pack_version CHECK (version_number >= 1),
    CONSTRAINT chk_strategy_performance_pack_status CHECK (lifecycle_status IN ('draft','approved','superseded'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_pack_kpis (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    performance_pack_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_observation_id BIGINT UNSIGNED NOT NULL,
    target_value_snapshot DECIMAL(24,8) NOT NULL,
    actual_value_snapshot DECIMAL(24,8) NOT NULL,
    forecast_value_snapshot DECIMAL(24,8) NULL,
    variance_value DECIMAL(24,8) NOT NULL,
    variance_percent DECIMAL(18,8) NULL,
    assessment VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    commentary TEXT NULL,
    source_domain VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_record_type VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_public_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_pack_kpi (performance_pack_id, strategy_kpi_id),
    KEY ix_strategy_performance_pack_kpi_assessment (performance_pack_id, assessment),
    CONSTRAINT fk_strategy_performance_pack_kpi_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_pack_kpi_pack FOREIGN KEY (performance_pack_id) REFERENCES strategy_performance_packs(id),
    CONSTRAINT fk_strategy_performance_pack_kpi_kpi FOREIGN KEY (strategy_kpi_id) REFERENCES strategy_kpis(id),
    CONSTRAINT fk_strategy_performance_pack_kpi_observation FOREIGN KEY (strategy_kpi_observation_id) REFERENCES strategy_kpi_observations(id),
    CONSTRAINT fk_strategy_performance_pack_kpi_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_pack_kpi_assessment CHECK (assessment IN ('on_track','watch','off_track','not_measured'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_variances (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    performance_pack_kpi_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    variance_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    materiality VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    cause_category VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    root_cause_text TEXT NOT NULL,
    impact_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'open',
    resolution_text TEXT NULL,
    closed_by_member_id BIGINT UNSIGNED NULL,
    closed_at DATETIME(6) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_variance_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_variance_code (organisation_id, variance_code),
    KEY ix_strategy_performance_variance_status (organisation_id, lifecycle_status, materiality),
    CONSTRAINT fk_strategy_performance_variance_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_variance_pack_kpi FOREIGN KEY (performance_pack_kpi_id) REFERENCES strategy_performance_pack_kpis(id),
    CONSTRAINT fk_strategy_performance_variance_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_variance_closed_by FOREIGN KEY (closed_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_variance_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_variance_materiality CHECK (materiality IN ('low','medium','high','critical')),
    CONSTRAINT chk_strategy_performance_variance_cause CHECK (cause_category IN ('volume','price','productivity','timing','scope','quality','external','forecast','other')),
    CONSTRAINT chk_strategy_performance_variance_status CHECK (lifecycle_status IN ('open','investigating','actioned','closed')),
    CONSTRAINT chk_strategy_performance_variance_closed CHECK (lifecycle_status <> 'closed' OR (closed_by_member_id IS NOT NULL AND closed_at IS NOT NULL AND resolution_text IS NOT NULL))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_actions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    performance_variance_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    action_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    action_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    due_date DATE NOT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'open',
    source_domain VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_record_type VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_public_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    completion_evidence TEXT NULL,
    completed_by_member_id BIGINT UNSIGNED NULL,
    completed_at DATETIME(6) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_action_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_action_code (performance_variance_id, action_code),
    KEY ix_strategy_performance_action_status (organisation_id, lifecycle_status, due_date),
    CONSTRAINT fk_strategy_performance_action_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_action_variance FOREIGN KEY (performance_variance_id) REFERENCES strategy_performance_variances(id),
    CONSTRAINT fk_strategy_performance_action_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_action_completed_by FOREIGN KEY (completed_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_action_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_action_status CHECK (lifecycle_status IN ('open','in_progress','completed','cancelled')),
    CONSTRAINT chk_strategy_performance_action_completion CHECK (lifecycle_status <> 'completed' OR (completion_evidence IS NOT NULL AND completed_by_member_id IS NOT NULL AND completed_at IS NOT NULL))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_reviews (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    performance_pack_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    decision_text TEXT NULL,
    governance_meeting_public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    governance_decision_public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    approved_by_member_id BIGINT UNSIGNED NULL,
    approved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_review_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_review_code (organisation_id, review_code),
    KEY ix_strategy_performance_review_date (organisation_id, review_date, lifecycle_status),
    CONSTRAINT fk_strategy_performance_review_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_review_pack FOREIGN KEY (performance_pack_id) REFERENCES strategy_performance_packs(id),
    CONSTRAINT fk_strategy_performance_review_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_review_approved_by FOREIGN KEY (approved_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_review_status CHECK (lifecycle_status IN ('draft','approved'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_benchmarks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    benchmark_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    benchmark_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    scope_text TEXT NOT NULL,
    unit_label VARCHAR(64) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    benchmark_value DECIMAL(24,8) NOT NULL,
    provenance_text TEXT NOT NULL,
    source_reference VARCHAR(512) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_benchmark_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_benchmark_code (organisation_id, benchmark_code),
    KEY ix_strategy_performance_benchmark_kpi (strategy_kpi_id, period_end),
    CONSTRAINT fk_strategy_performance_benchmark_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_benchmark_kpi FOREIGN KEY (strategy_kpi_id) REFERENCES strategy_kpis(id),
    CONSTRAINT fk_strategy_performance_benchmark_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_benchmark_type CHECK (benchmark_type IN ('internal','external','peer','industry','target')),
    CONSTRAINT chk_strategy_performance_benchmark_dates CHECK (period_end >= period_start)
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_benchmark_results (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    performance_benchmark_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_observation_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    gap_value DECIMAL(24,8) NOT NULL,
    gap_percent DECIMAL(18,8) NULL,
    interpretation TEXT NOT NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_benchmark_result_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_benchmark_result (performance_benchmark_id, strategy_kpi_observation_id),
    CONSTRAINT fk_strategy_performance_benchmark_result_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_benchmark_result_benchmark FOREIGN KEY (performance_benchmark_id) REFERENCES strategy_performance_benchmarks(id),
    CONSTRAINT fk_strategy_performance_benchmark_result_observation FOREIGN KEY (strategy_kpi_observation_id) REFERENCES strategy_kpi_observations(id),
    CONSTRAINT fk_strategy_performance_benchmark_result_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id)
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_benefits (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    strategy_kpi_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    benefit_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    benefit_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    unit_label VARCHAR(64) NOT NULL,
    baseline_value DECIMAL(24,8) NOT NULL,
    target_value DECIMAL(24,8) NOT NULL,
    target_date DATE NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    review_cadence VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_domain VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_record_type VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_public_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    lifecycle_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'active',
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_benefit_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_benefit_code (organisation_id, benefit_code),
    KEY ix_strategy_performance_benefit_kpi (strategy_kpi_id, lifecycle_status, target_date),
    CONSTRAINT fk_strategy_performance_benefit_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_benefit_kpi FOREIGN KEY (strategy_kpi_id) REFERENCES strategy_kpis(id),
    CONSTRAINT fk_strategy_performance_benefit_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_strategy_performance_benefit_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_benefit_type CHECK (benefit_type IN ('financial','operational','customer','people','risk','sustainability','other')),
    CONSTRAINT chk_strategy_performance_benefit_cadence CHECK (review_cadence IN ('weekly','monthly','quarterly','annual')),
    CONSTRAINT chk_strategy_performance_benefit_status CHECK (lifecycle_status IN ('active','achieved','closed','cancelled'))
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE strategy_performance_benefit_measurements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    performance_benefit_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    measured_on DATE NOT NULL,
    realised_value DECIMAL(24,8) NOT NULL,
    confidence_percent DECIMAL(6,3) NOT NULL,
    evidence_text TEXT NOT NULL,
    source_domain VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_record_type VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_public_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_strategy_performance_benefit_measurement_public (organisation_id, public_id),
    UNIQUE KEY uq_strategy_performance_benefit_measurement_date (performance_benefit_id, measured_on),
    CONSTRAINT fk_strategy_performance_benefit_measurement_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_strategy_performance_benefit_measurement_benefit FOREIGN KEY (performance_benefit_id) REFERENCES strategy_performance_benefits(id),
    CONSTRAINT fk_strategy_performance_benefit_measurement_created_by FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_strategy_performance_benefit_measurement_confidence CHECK (confidence_percent >= 0 AND confidence_percent <= 100)
)
ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- migrate:down transaction:false
-- Approved enterprise-performance evidence is forward-only. Non-production environments
-- are rebuilt from the authoritative migration stream rather than destructively rolling back.
SELECT 1;
