-- migrate:up

CREATE TABLE corporate_development_diligence_workstreams (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    opportunity_id BIGINT UNSIGNED NOT NULL,
    workstream_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    diligence_domain VARCHAR(30) NOT NULL,
    scope_text TEXT NOT NULL,
    lead_member_id BIGINT UNSIGNED NOT NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'open',
    planned_start_date DATE NULL,
    planned_end_date DATE NULL,
    completed_at TIMESTAMP NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_diligence_workstream_public (public_id),
    UNIQUE KEY uq_corpdev_diligence_workstream_code (organisation_id, opportunity_id, workstream_code),
    KEY idx_corpdev_diligence_workstream (organisation_id, opportunity_id, lifecycle_status),
    CONSTRAINT fk_corpdev_diligence_workstream_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_diligence_workstream_opportunity FOREIGN KEY (opportunity_id) REFERENCES corporate_development_opportunities(id),
    CONSTRAINT fk_corpdev_diligence_workstream_lead FOREIGN KEY (lead_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_diligence_workstream_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_diligence_domain CHECK (diligence_domain IN ('finance_tax','legal_commercial','compliance_qhse','workforce','technology_data','operations','property_assets','insurance','sustainability','other')),
    CONSTRAINT chk_corpdev_diligence_workstream_status CHECK (lifecycle_status IN ('open','in_progress','blocked','complete','cancelled'))
);

CREATE TABLE corporate_development_diligence_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    diligence_workstream_id BIGINT UNSIGNED NOT NULL,
    request_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    request_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    materiality VARCHAR(20) NOT NULL DEFAULT 'medium',
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'requested',
    requested_on DATE NOT NULL,
    due_date DATE NULL,
    responded_at TIMESTAMP NULL,
    response_text TEXT NULL,
    evidence_source_domain VARCHAR(50) NULL,
    evidence_record_type VARCHAR(80) NULL,
    evidence_public_id VARCHAR(100) NULL,
    evidence_reference VARCHAR(500) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_diligence_request_public (public_id),
    UNIQUE KEY uq_corpdev_diligence_request_code (organisation_id, diligence_workstream_id, request_code),
    KEY idx_corpdev_diligence_request (organisation_id, diligence_workstream_id, lifecycle_status, due_date),
    CONSTRAINT fk_corpdev_diligence_request_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_diligence_request_workstream FOREIGN KEY (diligence_workstream_id) REFERENCES corporate_development_diligence_workstreams(id),
    CONSTRAINT fk_corpdev_diligence_request_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_diligence_request_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_diligence_request_materiality CHECK (materiality IN ('low','medium','high','critical')),
    CONSTRAINT chk_corpdev_diligence_request_status CHECK (lifecycle_status IN ('requested','in_progress','responded','accepted','rejected','waived','cancelled'))
);

CREATE TABLE corporate_development_diligence_findings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    diligence_workstream_id BIGINT UNSIGNED NOT NULL,
    diligence_request_id BIGINT UNSIGNED NULL,
    finding_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    finding_category VARCHAR(30) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    finding_text TEXT NOT NULL,
    impact_text TEXT NOT NULL,
    recommendation_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'open',
    transaction_implication TEXT NULL,
    resolution_text TEXT NULL,
    resolved_at TIMESTAMP NULL,
    evidence_source_domain VARCHAR(50) NULL,
    evidence_record_type VARCHAR(80) NULL,
    evidence_public_id VARCHAR(100) NULL,
    evidence_reference VARCHAR(500) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_diligence_finding_public (public_id),
    UNIQUE KEY uq_corpdev_diligence_finding_code (organisation_id, diligence_workstream_id, finding_code),
    KEY idx_corpdev_diligence_finding (organisation_id, diligence_workstream_id, severity, lifecycle_status),
    CONSTRAINT fk_corpdev_diligence_finding_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_diligence_finding_workstream FOREIGN KEY (diligence_workstream_id) REFERENCES corporate_development_diligence_workstreams(id),
    CONSTRAINT fk_corpdev_diligence_finding_request FOREIGN KEY (diligence_request_id) REFERENCES corporate_development_diligence_requests(id),
    CONSTRAINT fk_corpdev_diligence_finding_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_diligence_finding_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_diligence_finding_category CHECK (finding_category IN ('risk','issue','opportunity','dependency','assumption','red_flag','other')),
    CONSTRAINT chk_corpdev_diligence_finding_severity CHECK (severity IN ('low','medium','high','critical')),
    CONSTRAINT chk_corpdev_diligence_finding_status CHECK (lifecycle_status IN ('open','mitigating','resolved','accepted','closed'))
);

CREATE TABLE corporate_development_transactions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    opportunity_id BIGINT UNSIGNED NOT NULL,
    transaction_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    transaction_type VARCHAR(30) NOT NULL,
    transaction_structure VARCHAR(50) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    consideration_value DECIMAL(20,4) NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'draft',
    offer_date DATE NULL,
    signing_date DATE NULL,
    expected_close_date DATE NULL,
    actual_close_date DATE NULL,
    governance_meeting_public_id VARCHAR(100) NULL,
    governance_decision_public_id VARCHAR(100) NULL,
    delegation_authority_public_id VARCHAR(100) NULL,
    contract_source_domain VARCHAR(50) NULL,
    contract_record_type VARCHAR(80) NULL,
    contract_public_id VARCHAR(100) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_transaction_public (public_id),
    UNIQUE KEY uq_corpdev_transaction_code (organisation_id, transaction_code),
    KEY idx_corpdev_transaction_opportunity (organisation_id, opportunity_id, lifecycle_status),
    CONSTRAINT fk_corpdev_transaction_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_transaction_opportunity FOREIGN KEY (opportunity_id) REFERENCES corporate_development_opportunities(id),
    CONSTRAINT fk_corpdev_transaction_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_transaction_type CHECK (transaction_type IN ('acquisition','divestiture','joint_venture','minority_investment','strategic_partnership','other')),
    CONSTRAINT chk_corpdev_transaction_status CHECK (lifecycle_status IN ('draft','negotiating','approval','signed','closing','closed','terminated','withdrawn'))
);

CREATE TABLE corporate_development_transaction_terms (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    transaction_id BIGINT UNSIGNED NOT NULL,
    term_code VARCHAR(50) NOT NULL,
    term_type VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    term_text TEXT NOT NULL,
    numeric_value DECIMAL(20,4) NULL,
    currency_code CHAR(3) NULL,
    source_reference VARCHAR(500) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_transaction_term_public (public_id),
    UNIQUE KEY uq_corpdev_transaction_term_code (organisation_id, transaction_id, term_code),
    CONSTRAINT fk_corpdev_transaction_term_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_transaction_term_transaction FOREIGN KEY (transaction_id) REFERENCES corporate_development_transactions(id),
    CONSTRAINT fk_corpdev_transaction_term_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_transaction_term_type CHECK (term_type IN ('price','payment','earnout','warranty','indemnity','covenant','termination','exclusivity','governance','other'))
);

CREATE TABLE corporate_development_transaction_milestones (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    transaction_id BIGINT UNSIGNED NOT NULL,
    milestone_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    milestone_type VARCHAR(30) NOT NULL,
    planned_date DATE NOT NULL,
    actual_date DATE NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'planned',
    evidence_reference VARCHAR(500) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_transaction_milestone_public (public_id),
    UNIQUE KEY uq_corpdev_transaction_milestone_code (organisation_id, transaction_id, milestone_code),
    CONSTRAINT fk_corpdev_transaction_milestone_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_transaction_milestone_transaction FOREIGN KEY (transaction_id) REFERENCES corporate_development_transactions(id),
    CONSTRAINT fk_corpdev_transaction_milestone_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_transaction_milestone_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_transaction_milestone_type CHECK (milestone_type IN ('indicative_offer','binding_offer','exclusivity','approval','signing','regulatory','financing','closing','other')),
    CONSTRAINT chk_corpdev_transaction_milestone_status CHECK (lifecycle_status IN ('planned','in_progress','complete','missed','cancelled'))
);

CREATE TABLE corporate_development_transaction_conditions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    transaction_id BIGINT UNSIGNED NOT NULL,
    condition_code VARCHAR(50) NOT NULL,
    condition_type VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    condition_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    due_date DATE NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'open',
    satisfied_at TIMESTAMP NULL,
    evidence_source_domain VARCHAR(50) NULL,
    evidence_record_type VARCHAR(80) NULL,
    evidence_public_id VARCHAR(100) NULL,
    evidence_reference VARCHAR(500) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_transaction_condition_public (public_id),
    UNIQUE KEY uq_corpdev_transaction_condition_code (organisation_id, transaction_id, condition_code),
    CONSTRAINT fk_corpdev_transaction_condition_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_transaction_condition_transaction FOREIGN KEY (transaction_id) REFERENCES corporate_development_transactions(id),
    CONSTRAINT fk_corpdev_transaction_condition_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_transaction_condition_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_transaction_condition_type CHECK (condition_type IN ('precedent','subsequent','covenant','regulatory','financing','other')),
    CONSTRAINT chk_corpdev_transaction_condition_status CHECK (lifecycle_status IN ('open','in_progress','satisfied','waived','failed','cancelled'))
);

CREATE TABLE corporate_development_integration_plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    opportunity_id BIGINT UNSIGNED NOT NULL,
    transaction_id BIGINT UNSIGNED NULL,
    integration_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    integration_thesis TEXT NOT NULL,
    day_one_date DATE NULL,
    day_one_outcomes TEXT NOT NULL,
    day_one_hundred_date DATE NULL,
    day_one_hundred_outcomes TEXT NOT NULL,
    target_operating_model_date DATE NULL,
    target_operating_model_outcomes TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'planning',
    delivery_source_domain VARCHAR(50) NULL,
    delivery_record_type VARCHAR(80) NULL,
    delivery_public_id VARCHAR(100) NULL,
    performance_benefit_public_id VARCHAR(100) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_integration_plan_public (public_id),
    UNIQUE KEY uq_corpdev_integration_plan_code (organisation_id, integration_code),
    CONSTRAINT fk_corpdev_integration_plan_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_integration_plan_opportunity FOREIGN KEY (opportunity_id) REFERENCES corporate_development_opportunities(id),
    CONSTRAINT fk_corpdev_integration_plan_transaction FOREIGN KEY (transaction_id) REFERENCES corporate_development_transactions(id),
    CONSTRAINT fk_corpdev_integration_plan_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_integration_plan_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_integration_plan_status CHECK (lifecycle_status IN ('planning','day_one_ready','executing','stabilising','complete','cancelled'))
);

CREATE TABLE corporate_development_integration_workstreams (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    integration_plan_id BIGINT UNSIGNED NOT NULL,
    workstream_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    functional_area VARCHAR(80) NOT NULL,
    outcomes_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    planned_start_date DATE NULL,
    planned_end_date DATE NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'planned',
    dependency_text TEXT NULL,
    delivery_source_domain VARCHAR(50) NULL,
    delivery_record_type VARCHAR(80) NULL,
    delivery_public_id VARCHAR(100) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_integration_workstream_public (public_id),
    UNIQUE KEY uq_corpdev_integration_workstream_code (organisation_id, integration_plan_id, workstream_code),
    CONSTRAINT fk_corpdev_integration_workstream_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_integration_workstream_plan FOREIGN KEY (integration_plan_id) REFERENCES corporate_development_integration_plans(id),
    CONSTRAINT fk_corpdev_integration_workstream_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_integration_workstream_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_integration_workstream_status CHECK (lifecycle_status IN ('planned','in_progress','blocked','complete','cancelled'))
);

CREATE TABLE corporate_development_divestiture_plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    opportunity_id BIGINT UNSIGNED NOT NULL,
    transaction_id BIGINT UNSIGNED NULL,
    divestiture_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    perimeter_text TEXT NOT NULL,
    separation_strategy TEXT NOT NULL,
    buyer_name VARCHAR(255) NULL,
    buyer_source_domain VARCHAR(50) NULL,
    buyer_source_record_type VARCHAR(80) NULL,
    buyer_source_public_id VARCHAR(100) NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    target_separation_date DATE NULL,
    actual_separation_date DATE NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'planning',
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_divestiture_plan_public (public_id),
    UNIQUE KEY uq_corpdev_divestiture_plan_code (organisation_id, divestiture_code),
    CONSTRAINT fk_corpdev_divestiture_plan_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_divestiture_plan_opportunity FOREIGN KEY (opportunity_id) REFERENCES corporate_development_opportunities(id),
    CONSTRAINT fk_corpdev_divestiture_plan_transaction FOREIGN KEY (transaction_id) REFERENCES corporate_development_transactions(id),
    CONSTRAINT fk_corpdev_divestiture_plan_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_divestiture_plan_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_divestiture_plan_status CHECK (lifecycle_status IN ('planning','preparing','separating','transition','complete','cancelled'))
);

CREATE TABLE corporate_development_separation_obligations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    divestiture_plan_id BIGINT UNSIGNED NOT NULL,
    obligation_code VARCHAR(50) NOT NULL,
    obligation_type VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    obligation_text TEXT NOT NULL,
    counterparty_name VARCHAR(255) NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    due_date DATE NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'open',
    completed_at TIMESTAMP NULL,
    evidence_source_domain VARCHAR(50) NULL,
    evidence_record_type VARCHAR(80) NULL,
    evidence_public_id VARCHAR(100) NULL,
    evidence_reference VARCHAR(500) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_separation_obligation_public (public_id),
    UNIQUE KEY uq_corpdev_separation_obligation_code (organisation_id, divestiture_plan_id, obligation_code),
    CONSTRAINT fk_corpdev_separation_obligation_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_separation_obligation_plan FOREIGN KEY (divestiture_plan_id) REFERENCES corporate_development_divestiture_plans(id),
    CONSTRAINT fk_corpdev_separation_obligation_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_separation_obligation_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_separation_obligation_type CHECK (obligation_type IN ('tsa','data_migration','systems','people','property','contract','brand','regulatory','finance','tax','other')),
    CONSTRAINT chk_corpdev_separation_obligation_status CHECK (lifecycle_status IN ('open','in_progress','blocked','complete','waived','cancelled'))
);

CREATE TABLE corporate_development_partnerships (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    opportunity_id BIGINT UNSIGNED NULL,
    partnership_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    partner_name VARCHAR(255) NOT NULL,
    partner_source_domain VARCHAR(50) NULL,
    partner_source_record_type VARCHAR(80) NULL,
    partner_source_public_id VARCHAR(100) NULL,
    partnership_type VARCHAR(30) NOT NULL,
    objectives_text TEXT NOT NULL,
    commercial_structure TEXT NOT NULL,
    governance_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    review_cadence VARCHAR(20) NOT NULL DEFAULT 'quarterly',
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'draft',
    governance_decision_public_id VARCHAR(100) NULL,
    contract_source_domain VARCHAR(50) NULL,
    contract_record_type VARCHAR(80) NULL,
    contract_public_id VARCHAR(100) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_partnership_public (public_id),
    UNIQUE KEY uq_corpdev_partnership_code (organisation_id, partnership_code),
    KEY idx_corpdev_partnership_status (organisation_id, lifecycle_status, effective_from),
    CONSTRAINT fk_corpdev_partnership_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_partnership_opportunity FOREIGN KEY (opportunity_id) REFERENCES corporate_development_opportunities(id),
    CONSTRAINT fk_corpdev_partnership_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_partnership_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_partnership_type CHECK (partnership_type IN ('strategic_alliance','joint_venture','channel','technology','supply','research','consortium','other')),
    CONSTRAINT chk_corpdev_partnership_cadence CHECK (review_cadence IN ('monthly','quarterly','semiannual','annual')),
    CONSTRAINT chk_corpdev_partnership_status CHECK (lifecycle_status IN ('draft','approval','active','suspended','expired','terminated','closed')),
    CONSTRAINT chk_corpdev_partnership_dates CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE corporate_development_partnership_commitments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    partnership_id BIGINT UNSIGNED NOT NULL,
    commitment_code VARCHAR(50) NOT NULL,
    commitment_type VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    commitment_text TEXT NOT NULL,
    owner_member_id BIGINT UNSIGNED NOT NULL,
    due_date DATE NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'open',
    commercial_value DECIMAL(20,4) NULL,
    currency_code CHAR(3) NULL,
    source_reference VARCHAR(500) NULL,
    completed_at TIMESTAMP NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_partnership_commitment_public (public_id),
    UNIQUE KEY uq_corpdev_partnership_commitment_code (organisation_id, partnership_id, commitment_code),
    CONSTRAINT fk_corpdev_partnership_commitment_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_partnership_commitment_partnership FOREIGN KEY (partnership_id) REFERENCES corporate_development_partnerships(id),
    CONSTRAINT fk_corpdev_partnership_commitment_owner FOREIGN KEY (owner_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_partnership_commitment_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_partnership_commitment_type CHECK (commitment_type IN ('financial','commercial','delivery','resource','technology','data','governance','marketing','exclusivity','other')),
    CONSTRAINT chk_corpdev_partnership_commitment_status CHECK (lifecycle_status IN ('open','in_progress','complete','waived','breached','cancelled'))
);

CREATE TABLE corporate_development_partnership_reviews (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    organisation_id BIGINT UNSIGNED NOT NULL,
    partnership_id BIGINT UNSIGNED NOT NULL,
    review_code VARCHAR(50) NOT NULL,
    review_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary_text TEXT NOT NULL,
    outcome VARCHAR(30) NOT NULL,
    decision_text TEXT NULL,
    reviewer_member_id BIGINT UNSIGNED NOT NULL,
    next_review_date DATE NULL,
    governance_decision_public_id VARCHAR(100) NULL,
    performance_evidence_public_id VARCHAR(100) NULL,
    created_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_corpdev_partnership_review_public (public_id),
    UNIQUE KEY uq_corpdev_partnership_review_code (organisation_id, partnership_id, review_code),
    CONSTRAINT fk_corpdev_partnership_review_org FOREIGN KEY (organisation_id) REFERENCES organisations(id),
    CONSTRAINT fk_corpdev_partnership_review_partnership FOREIGN KEY (partnership_id) REFERENCES corporate_development_partnerships(id),
    CONSTRAINT fk_corpdev_partnership_review_reviewer FOREIGN KEY (reviewer_member_id) REFERENCES organisation_members(id),
    CONSTRAINT fk_corpdev_partnership_review_created FOREIGN KEY (created_by_member_id) REFERENCES organisation_members(id),
    CONSTRAINT chk_corpdev_partnership_review_outcome CHECK (outcome IN ('continue','improve','renew','renegotiate','suspend','terminate','close'))
);

-- migrate:down
DROP TABLE IF EXISTS corporate_development_partnership_reviews;
DROP TABLE IF EXISTS corporate_development_partnership_commitments;
DROP TABLE IF EXISTS corporate_development_partnerships;
DROP TABLE IF EXISTS corporate_development_separation_obligations;
DROP TABLE IF EXISTS corporate_development_divestiture_plans;
DROP TABLE IF EXISTS corporate_development_integration_workstreams;
DROP TABLE IF EXISTS corporate_development_integration_plans;
DROP TABLE IF EXISTS corporate_development_transaction_conditions;
DROP TABLE IF EXISTS corporate_development_transaction_milestones;
DROP TABLE IF EXISTS corporate_development_transaction_terms;
DROP TABLE IF EXISTS corporate_development_transactions;
DROP TABLE IF EXISTS corporate_development_diligence_findings;
DROP TABLE IF EXISTS corporate_development_diligence_requests;
DROP TABLE IF EXISTS corporate_development_diligence_workstreams;