-- NuBlox: Digital Applications
-- Schema package 001: Platform Kernel
-- Target: MySQL 8.4 / InnoDB
-- Design target: 3NF by default
-- Generated: 2026-08-15
--
-- IMPORTANT:
-- 1. Authentication-provider-specific credential/session tables are intentionally omitted
--    until the authentication ADR is resolved.
-- 2. public_id values are generated by the application. UUIDv7 is preferred once the
--    implementation library/format is formally selected.
-- 3. All application timestamps are UTC.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- -----------------------------------------------------------------------------
-- Identity
-- -----------------------------------------------------------------------------

CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'active',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_users_public_id (public_id),
    CONSTRAINT ck_users_status
        CHECK (status IN ('pending', 'active', 'suspended', 'disabled'))
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE user_emails (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    email VARCHAR(320) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at DATETIME(6) NULL,
    primary_user_id BIGINT UNSIGNED
        GENERATED ALWAYS AS (
            CASE WHEN is_primary = TRUE THEN user_id ELSE NULL END
        ) STORED,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_user_emails_email (email),
    UNIQUE KEY uq_user_emails_one_primary (primary_user_id),
    KEY idx_user_emails_user (user_id),

    CONSTRAINT fk_user_emails_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT ck_user_emails_verified_at
        CHECK (
            (is_verified = FALSE AND verified_at IS NULL)
            OR is_verified = TRUE
        )
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- Organisations and tenant-owned locations
-- -----------------------------------------------------------------------------

CREATE TABLE organisations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    legal_name VARCHAR(255) NOT NULL,
    trading_name VARCHAR(255) NULL,
    default_timezone VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Europe/London',
    default_currency_code CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'GBP',
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'active',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_organisations_public_id (public_id),
    CONSTRAINT ck_organisations_status
        CHECK (status IN ('pending', 'active', 'suspended', 'archived'))
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE organisation_identifiers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    identifier_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    identifier_value VARCHAR(160) NOT NULL,
    issuing_country_code CHAR(2) CHARACTER SET ascii COLLATE ascii_bin NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_organisation_identifier (
        organisation_id,
        identifier_type,
        identifier_value
    ),
    KEY idx_organisation_identifiers_type_value (
        identifier_type,
        identifier_value
    ),

    CONSTRAINT fk_organisation_identifiers_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES organisations (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE addresses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    line_1 VARCHAR(255) NOT NULL,
    line_2 VARCHAR(255) NULL,
    line_3 VARCHAR(255) NULL,
    locality VARCHAR(160) NULL,
    city VARCHAR(160) NULL,
    region VARCHAR(160) NULL,
    postal_code VARCHAR(32) NULL,
    country_code CHAR(2) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_addresses_id_organisation (id, organisation_id),
    KEY idx_addresses_organisation_postcode (organisation_id, postal_code),

    CONSTRAINT fk_addresses_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES organisations (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE organisation_locations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    address_id BIGINT UNSIGNED NULL,
    name VARCHAR(200) NOT NULL,
    location_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'office',
    timezone VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_organisation_locations_public_id (public_id),
    UNIQUE KEY uq_organisation_locations_id_organisation (id, organisation_id),
    UNIQUE KEY uq_organisation_locations_name (organisation_id, name),
    KEY idx_organisation_locations_address (address_id, organisation_id),

    CONSTRAINT fk_organisation_locations_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES organisations (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_organisation_locations_address
        FOREIGN KEY (address_id, organisation_id)
        REFERENCES addresses (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- Organisation membership and teams
-- -----------------------------------------------------------------------------

CREATE TABLE organisation_members (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'invited',
    joined_at DATETIME(6) NULL,
    disabled_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_organisation_members_public_id (public_id),
    UNIQUE KEY uq_organisation_members_user (organisation_id, user_id),
    UNIQUE KEY uq_organisation_members_id_organisation (id, organisation_id),
    KEY idx_organisation_members_user (user_id),
    KEY idx_organisation_members_organisation_status (organisation_id, status),

    CONSTRAINT fk_organisation_members_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES organisations (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_organisation_members_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT ck_organisation_members_status
        CHECK (status IN ('invited', 'active', 'suspended', 'disabled', 'left'))
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE teams (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_teams_public_id (public_id),
    UNIQUE KEY uq_teams_id_organisation (id, organisation_id),
    UNIQUE KEY uq_teams_name (organisation_id, name),

    CONSTRAINT fk_teams_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES organisations (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE team_members (
    organisation_id BIGINT UNSIGNED NOT NULL,
    team_id BIGINT UNSIGNED NOT NULL,
    organisation_member_id BIGINT UNSIGNED NOT NULL,
    assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (organisation_id, team_id, organisation_member_id),
    KEY idx_team_members_member (organisation_id, organisation_member_id, team_id),

    CONSTRAINT fk_team_members_team
        FOREIGN KEY (team_id, organisation_id)
        REFERENCES teams (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_team_members_member
        FOREIGN KEY (organisation_member_id, organisation_id)
        REFERENCES organisation_members (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- Career taxonomy
-- -----------------------------------------------------------------------------

CREATE TABLE taxonomy_sources (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(200) NOT NULL,
    source_url VARCHAR(1000) NOT NULL,
    licence_name VARCHAR(200) NULL,
    licence_url VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_taxonomy_sources_key (source_key),
    UNIQUE KEY uq_taxonomy_sources_name (name)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE professional_domains (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    domain_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_professional_domains_code (domain_code),
    UNIQUE KEY uq_professional_domains_name (name)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE careers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_id BIGINT UNSIGNED NOT NULL,
    slug VARCHAR(200) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    canonical_name VARCHAR(255) NOT NULL,
    source_profile_url VARCHAR(1000) NULL,
    source_last_verified_at DATE NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_careers_source_slug (source_id, slug),
    UNIQUE KEY uq_careers_source_name (source_id, canonical_name),

    CONSTRAINT fk_careers_source
        FOREIGN KEY (source_id)
        REFERENCES taxonomy_sources (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE career_aliases (
    career_id BIGINT UNSIGNED NOT NULL,
    alias VARCHAR(255) NOT NULL,
    locale VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'en-GB',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (career_id, alias, locale),
    KEY idx_career_aliases_alias (alias),

    CONSTRAINT fk_career_aliases_career
        FOREIGN KEY (career_id)
        REFERENCES careers (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE career_domains (
    career_id BIGINT UNSIGNED NOT NULL,
    professional_domain_id BIGINT UNSIGNED NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    primary_career_id BIGINT UNSIGNED
        GENERATED ALWAYS AS (
            CASE WHEN is_primary = TRUE THEN career_id ELSE NULL END
        ) STORED,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (career_id, professional_domain_id),
    UNIQUE KEY uq_career_domains_one_primary (primary_career_id),
    KEY idx_career_domains_domain (professional_domain_id, career_id),

    CONSTRAINT fk_career_domains_career
        FOREIGN KEY (career_id)
        REFERENCES careers (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_career_domains_domain
        FOREIGN KEY (professional_domain_id)
        REFERENCES professional_domains (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- Application capabilities and authorisation permissions
-- -----------------------------------------------------------------------------

CREATE TABLE application_modules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    module_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_application_modules_key (module_key),
    UNIQUE KEY uq_application_modules_name (name)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE capabilities (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    application_module_id BIGINT UNSIGNED NOT NULL,
    capability_key VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_capabilities_key (capability_key),
    KEY idx_capabilities_module (application_module_id, is_active),

    CONSTRAINT fk_capabilities_module
        FOREIGN KEY (application_module_id)
        REFERENCES application_modules (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE career_capabilities (
    career_id BIGINT UNSIGNED NOT NULL,
    capability_id BIGINT UNSIGNED NOT NULL,
    enabled_by_default BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (career_id, capability_id),
    KEY idx_career_capabilities_capability (capability_id, career_id),

    CONSTRAINT fk_career_capabilities_career
        FOREIGN KEY (career_id)
        REFERENCES careers (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_career_capabilities_capability
        FOREIGN KEY (capability_id)
        REFERENCES capabilities (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE member_careers (
    organisation_id BIGINT UNSIGNED NOT NULL,
    organisation_member_id BIGINT UNSIGNED NOT NULL,
    career_id BIGINT UNSIGNED NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    primary_member_id BIGINT UNSIGNED
        GENERATED ALWAYS AS (
            CASE WHEN is_primary = TRUE THEN organisation_member_id ELSE NULL END
        ) STORED,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (organisation_id, organisation_member_id, career_id),
    UNIQUE KEY uq_member_careers_one_primary (primary_member_id),
    KEY idx_member_careers_career (career_id, organisation_id),

    CONSTRAINT fk_member_careers_member
        FOREIGN KEY (organisation_member_id, organisation_id)
        REFERENCES organisation_members (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_member_careers_career
        FOREIGN KEY (career_id)
        REFERENCES careers (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE permissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    capability_id BIGINT UNSIGNED NULL,
    permission_key VARCHAR(180) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_permissions_key (permission_key),
    KEY idx_permissions_capability (capability_id, is_active),

    CONSTRAINT fk_permissions_capability
        FOREIGN KEY (capability_id)
        REFERENCES capabilities (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE organisation_roles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organisation_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_organisation_roles_public_id (public_id),
    UNIQUE KEY uq_organisation_roles_id_organisation (id, organisation_id),
    UNIQUE KEY uq_organisation_roles_name (organisation_id, name),

    CONSTRAINT fk_organisation_roles_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES organisations (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE role_permissions (
    organisation_id BIGINT UNSIGNED NOT NULL,
    organisation_role_id BIGINT UNSIGNED NOT NULL,
    permission_id BIGINT UNSIGNED NOT NULL,
    granted_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (organisation_id, organisation_role_id, permission_id),
    KEY idx_role_permissions_permission (permission_id, organisation_id),

    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (organisation_role_id, organisation_id)
        REFERENCES organisation_roles (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id)
        REFERENCES permissions (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE member_roles (
    organisation_id BIGINT UNSIGNED NOT NULL,
    organisation_member_id BIGINT UNSIGNED NOT NULL,
    organisation_role_id BIGINT UNSIGNED NOT NULL,
    assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (
        organisation_id,
        organisation_member_id,
        organisation_role_id
    ),
    KEY idx_member_roles_role (organisation_id, organisation_role_id, organisation_member_id),

    CONSTRAINT fk_member_roles_member
        FOREIGN KEY (organisation_member_id, organisation_id)
        REFERENCES organisation_members (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_member_roles_role
        FOREIGN KEY (organisation_role_id, organisation_id)
        REFERENCES organisation_roles (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE member_permission_overrides (
    organisation_id BIGINT UNSIGNED NOT NULL,
    organisation_member_id BIGINT UNSIGNED NOT NULL,
    permission_id BIGINT UNSIGNED NOT NULL,
    effect VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    reason VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (
        organisation_id,
        organisation_member_id,
        permission_id
    ),
    KEY idx_member_permission_overrides_permission (permission_id, organisation_id),

    CONSTRAINT fk_member_permission_overrides_member
        FOREIGN KEY (organisation_member_id, organisation_id)
        REFERENCES organisation_members (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_member_permission_overrides_permission
        FOREIGN KEY (permission_id)
        REFERENCES permissions (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT ck_member_permission_overrides_effect
        CHECK (effect IN ('allow', 'deny'))
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- Projects and cross-organisation participation
-- -----------------------------------------------------------------------------

CREATE TABLE project_role_types (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    role_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_project_role_types_key (role_key),
    UNIQUE KEY uq_project_role_types_name (name)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE projects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    owning_organisation_id BIGINT UNSIGNED NOT NULL,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    project_number VARCHAR(80) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'proposed',
    created_by_member_id BIGINT UNSIGNED NULL,
    started_on DATE NULL,
    completed_on DATE NULL,
    archived_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    UNIQUE KEY uq_projects_public_id (public_id),
    UNIQUE KEY uq_projects_number (owning_organisation_id, project_number),
    KEY idx_projects_organisation_status (owning_organisation_id, status),
    KEY idx_projects_created_by (created_by_member_id, owning_organisation_id),

    CONSTRAINT fk_projects_organisation
        FOREIGN KEY (owning_organisation_id)
        REFERENCES organisations (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_projects_created_by_member
        FOREIGN KEY (created_by_member_id, owning_organisation_id)
        REFERENCES organisation_members (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT ck_projects_status
        CHECK (status IN ('proposed', 'active', 'on_hold', 'completed', 'cancelled', 'archived')),
    CONSTRAINT ck_projects_dates
        CHECK (
            completed_on IS NULL
            OR started_on IS NULL
            OR completed_on >= started_on
        )
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE project_organisations (
    project_id BIGINT UNSIGNED NOT NULL,
    participant_organisation_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'invited',
    invited_by_member_id BIGINT UNSIGNED NULL,
    joined_at DATETIME(6) NULL,
    left_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (project_id, participant_organisation_id),
    KEY idx_project_organisations_participant (
        participant_organisation_id,
        status,
        project_id
    ),
    KEY idx_project_organisations_inviter (invited_by_member_id),

    CONSTRAINT fk_project_organisations_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_project_organisations_participant
        FOREIGN KEY (participant_organisation_id)
        REFERENCES organisations (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_project_organisations_inviter
        FOREIGN KEY (invited_by_member_id)
        REFERENCES organisation_members (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT ck_project_organisations_status
        CHECK (status IN ('invited', 'active', 'suspended', 'left', 'removed')),
    CONSTRAINT ck_project_organisations_dates
        CHECK (left_at IS NULL OR joined_at IS NULL OR left_at >= joined_at)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE project_organisation_roles (
    project_id BIGINT UNSIGNED NOT NULL,
    participant_organisation_id BIGINT UNSIGNED NOT NULL,
    project_role_type_id BIGINT UNSIGNED NOT NULL,
    assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (
        project_id,
        participant_organisation_id,
        project_role_type_id
    ),
    KEY idx_project_organisation_roles_role (
        project_role_type_id,
        project_id
    ),

    CONSTRAINT fk_project_organisation_roles_participation
        FOREIGN KEY (project_id, participant_organisation_id)
        REFERENCES project_organisations (project_id, participant_organisation_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_project_organisation_roles_role
        FOREIGN KEY (project_role_type_id)
        REFERENCES project_role_types (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE project_members (
    project_id BIGINT UNSIGNED NOT NULL,
    participant_organisation_id BIGINT UNSIGNED NOT NULL,
    organisation_member_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'active',
    joined_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    left_at DATETIME(6) NULL,

    PRIMARY KEY (
        project_id,
        participant_organisation_id,
        organisation_member_id
    ),
    KEY idx_project_members_member (
        participant_organisation_id,
        organisation_member_id,
        project_id
    ),

    CONSTRAINT fk_project_members_project_organisation
        FOREIGN KEY (project_id, participant_organisation_id)
        REFERENCES project_organisations (project_id, participant_organisation_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_project_members_organisation_member
        FOREIGN KEY (organisation_member_id, participant_organisation_id)
        REFERENCES organisation_members (id, organisation_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT ck_project_members_status
        CHECK (status IN ('active', 'suspended', 'left', 'removed')),
    CONSTRAINT ck_project_members_dates
        CHECK (left_at IS NULL OR left_at >= joined_at)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE project_member_roles (
    project_id BIGINT UNSIGNED NOT NULL,
    participant_organisation_id BIGINT UNSIGNED NOT NULL,
    organisation_member_id BIGINT UNSIGNED NOT NULL,
    project_role_type_id BIGINT UNSIGNED NOT NULL,
    assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (
        project_id,
        participant_organisation_id,
        organisation_member_id,
        project_role_type_id
    ),
    KEY idx_project_member_roles_role (
        project_role_type_id,
        project_id
    ),

    CONSTRAINT fk_project_member_roles_member
        FOREIGN KEY (
            project_id,
            participant_organisation_id,
            organisation_member_id
        )
        REFERENCES project_members (
            project_id,
            participant_organisation_id,
            organisation_member_id
        )
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_project_member_roles_role
        FOREIGN KEY (project_role_type_id)
        REFERENCES project_role_types (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- Audit evidence
-- -----------------------------------------------------------------------------

CREATE TABLE audit_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    occurred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    acting_organisation_id BIGINT UNSIGNED NULL,
    actor_user_id BIGINT UNSIGNED NULL,
    actor_member_id BIGINT UNSIGNED NULL,
    project_id BIGINT UNSIGNED NULL,
    action_key VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    subject_type VARCHAR(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    subject_public_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL,
    correlation_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL,
    change_summary JSON NULL,
    event_metadata JSON NULL,

    PRIMARY KEY (id),
    UNIQUE KEY uq_audit_events_public_id (event_public_id),
    KEY idx_audit_events_organisation_time (acting_organisation_id, occurred_at, id),
    KEY idx_audit_events_project_time (project_id, occurred_at, id),
    KEY idx_audit_events_actor_time (actor_user_id, occurred_at, id),
    KEY idx_audit_events_subject (subject_type, subject_public_id, occurred_at),
    KEY idx_audit_events_correlation (correlation_id),

    CONSTRAINT fk_audit_events_organisation
        FOREIGN KEY (acting_organisation_id)
        REFERENCES organisations (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_audit_events_actor_user
        FOREIGN KEY (actor_user_id)
        REFERENCES users (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_audit_events_actor_member
        FOREIGN KEY (actor_member_id)
        REFERENCES organisation_members (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_audit_events_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- Required application invariants not completely expressible as simple FKs
-- -----------------------------------------------------------------------------
--
-- The application/domain layer MUST enforce and test the following:
--
-- 1. The owning organisation is inserted into project_organisations when a project
--    is created.
-- 2. invited_by_member_id in project_organisations must have authority in the
--    owning organisation/project context.
-- 3. Audit actor_member_id, when present, must correspond to actor_user_id and the
--    acting organisation context.
-- 4. At least one verified/usable identity method must exist before an account can
--    authenticate; exact rule depends on the authentication ADR.
-- 5. An active organisation should have a primary business location only if the
--    product workflow requires one; this is not a universal relational invariant.
-- 6. Effective permissions are resolved by policy. Recommended precedence:
--       explicit deny > explicit allow > role grant > default deny
--    followed by project/record-level scope checks.
--
-- These invariants require automated integration tests in addition to DDL constraints.
