-- NuBlox: Digital Applications
-- Schema package 001a: Reserved kernel integrity checkpoint
-- Depends on: 001-platform-kernel.sql
-- Target: MySQL 8.4 / InnoDB
-- Generated: 2026-08-15
--
-- No DDL is currently required in this checkpoint.
--
-- The project tenant candidate key required by later commercial packages is added
-- at the start of 003-sales-quotes.sql before any foreign keys reference it.
-- This file is retained only so the pre-development package history remains explicit;
-- it may be consolidated away when the final migration system is selected.
