<script lang="ts">
	let { data, form } = $props();
	function money(value: string, currency = data.case.currencyCode) { return new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(Number(value)); }
	function date(value: Date | string | null) { return value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium' }).format(new Date(value)) : '—'; }
	function taxPolicy(value: string) { return value === 'no_tax_adjustment' ? 'No tax adjustment' : 'Separate tax adjustment required'; }
</script>

<svelte:head><title>{data.case.invoiceNumber} bad debt · NuBlox</title></svelte:head>
<nav class="breadcrumbs"><a href="/finance/bad-debt">Bad debt</a><span>/</span><span>{data.case.invoiceNumber}</span></nav>
<section class="page-heading"><div><p class="eyebrow">Bad-debt case · {data.case.status}</p><h1>{data.case.invoiceNumber}</h1><p>{data.case.customerDisplayName} · current receivable <strong>{money(data.case.outstandingAmount)}</strong></p></div><a class="button secondary" href={`/finance/invoices/${data.case.invoicePublicId}`}>View invoice</a></section>
{#if form?.actionError}<div class="alert">{form.actionError}</div>{/if}

<section class="panel"><p class="eyebrow">Assessment evidence</p><h2>Case</h2><p>{data.case.openingReason}</p><p class="muted">Opened {date(data.case.openedAt)}{#if data.case.closedAt} · closed {date(data.case.closedAt)} — {data.case.closeReason}{/if}</p>{#if data.canManageCase}<form method="POST" action="?/close" class="inline-form"><label>Close reason<input name="reason" maxlength="1000" required /></label><button type="submit" class="danger">Close case</button></form>{/if}</section>

<section class="panel"><div class="section-heading"><div><p class="eyebrow">Step 1</p><h2>Write-off recommendations</h2><p class="muted">A recommendation is immutable assessment evidence. It does not change the receivable.</p></div></div>{#if data.canRecommend}<form method="POST" action="?/recommend" class="form-grid"><label>Amount<input name="amount" inputmode="decimal" required /></label><label class="wide">Reason<textarea name="reason" maxlength="1000" required /></label><button type="submit">Record recommendation</button></form>{/if}{#if data.recommendations.length === 0}<p class="muted">No write-off recommendation has been recorded.</p>{:else}<div class="evidence-list">{#each data.recommendations as rec}<article><div><strong>{money(rec.amount)}</strong><small>{date(rec.recommendedAt)} · {rec.isUsed ? 'authorised into write-off' : 'not yet authorised'}</small><p>{rec.reason}</p></div>{#if data.canAuthoriseWriteOff && !rec.isUsed}<form method="POST" action="?/authorise" class="action-form"><input type="hidden" name="recommendationPublicId" value={rec.publicId} /><label>Tax treatment<select name="taxTreatmentPolicy" required><option value="no_tax_adjustment">No tax adjustment</option><option value="separate_tax_adjustment_required">Separate tax adjustment required</option></select></label><label>Authorisation reason<textarea name="reason" maxlength="1000" required /></label><button type="submit">Authorise write-off</button></form>{/if}</article>{/each}</div>{/if}</section>

<section class="panel"><div class="section-heading"><div><p class="eyebrow">Step 2</p><h2>Authorised write-offs</h2><p class="muted">Active write-offs reduce operational receivable while preserving invoice, tax and payment history.</p></div></div>{#if data.writeOffs.length === 0}<p class="muted">No write-off has been authorised.</p>{:else}<div class="evidence-list">{#each data.writeOffs as item}<article><div><strong>{money(item.amount)}</strong><small>{date(item.authorisedAt)} · {taxPolicy(item.taxTreatmentPolicy)} · {item.isReversed ? `reversed ${date(item.reversedAt)}` : 'active'}</small><p>{item.reason}</p><p class="muted">Active cash recovery: {money(item.activeRecoveryAmount)}</p>{#if item.reversalReason}<p class="muted">Reversal: {item.reversalReason}</p>{/if}</div>{#if data.canReverseWriteOff && !item.isReversed}<form method="POST" action="?/reverseWriteOff" class="action-form"><input type="hidden" name="writeOffPublicId" value={item.publicId} /><label>Reversal reason<textarea name="reason" maxlength="1000" required /></label><button class="danger" type="submit">Reverse write-off</button></form>{/if}{#if data.canRecordRecovery && !item.isReversed && data.paymentCandidates.length > 0}<form method="POST" action="?/recover" class="action-form recovery"><input type="hidden" name="writeOffPublicId" value={item.publicId} /><label>Payment<select name="paymentPublicId" required>{#each data.paymentCandidates as payment}<option value={payment.paymentPublicId}>{payment.paymentReference ?? payment.paymentPublicId} · {money(payment.availableAmount, payment.currencyCode)} available</option>{/each}</select></label><label>Recovery amount<input name="amount" inputmode="decimal" required /></label><label>Recovery reason<textarea name="reason" maxlength="1000" required /></label><button type="submit">Record recovery</button></form>{/if}</article>{/each}</div>{/if}</section>

<section class="panel"><div class="section-heading"><div><p class="eyebrow">Step 3</p><h2>Recovery evidence</h2><p class="muted">Recovery consumes available cash from an existing payment receipt. It does not reopen the written-off customer receivable.</p></div></div>{#if data.recoveries.length === 0}<p class="muted">No later cash recovery has been recorded.</p>{:else}<div class="evidence-list">{#each data.recoveries as recovery}<article><div><strong>{money(recovery.amount)}</strong><small>{date(recovery.recoveredAt)} · payment {recovery.paymentReference ?? recovery.paymentPublicId} · {recovery.isReversed ? `reversed ${date(recovery.reversedAt)}` : 'active'}</small><p>{recovery.reason}</p>{#if recovery.reversalReason}<p class="muted">Reversal: {recovery.reversalReason}</p>{/if}</div>{#if data.canReverseRecovery && !recovery.isReversed}<form method="POST" action="?/reverseRecovery" class="action-form"><input type="hidden" name="recoveryPublicId" value={recovery.publicId} /><label>Reversal reason<textarea name="reason" maxlength="1000" required /></label><button class="danger" type="submit">Reverse recovery</button></form>{/if}</article>{/each}</div>{/if}</section>

<style>
	.breadcrumbs{display:flex;gap:.5rem;color:#667085;font-size:.9rem;margin-bottom:1rem}.breadcrumbs a{color:inherit}.page-heading,.section-heading,.evidence-list article{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.page-heading{margin-bottom:1rem}.page-heading h1,.panel h2{margin:.15rem 0}.eyebrow{text-transform:uppercase;letter-spacing:.08em;font-size:.72rem;font-weight:700;color:#667085;margin:0}.panel{border:1px solid #d0d5dd;border-radius:14px;background:#fff;padding:1rem;margin-bottom:1rem}.muted,small{color:#667085}.evidence-list{display:grid;gap:.8rem;margin-top:.8rem}.evidence-list article{border:1px solid #e4e7ec;border-radius:11px;padding:.85rem;background:#fafafa}.evidence-list p{margin:.4rem 0 0}.form-grid,.action-form,.inline-form{display:grid;gap:.6rem;margin:.8rem 0}.form-grid{grid-template-columns:12rem 1fr auto;align-items:end}.form-grid .wide{min-width:15rem}.action-form{min-width:18rem;max-width:27rem}.inline-form{grid-template-columns:1fr auto;align-items:end}.recovery{border-top:1px solid #e4e7ec;padding-top:.75rem}label{display:grid;gap:.3rem;font-size:.84rem;font-weight:650}input,select,textarea{font:inherit;padding:.58rem;border:1px solid #d0d5dd;border-radius:8px;background:#fff}textarea{min-height:4rem}.alert{padding:.75rem 1rem;border:1px solid #fda29b;background:#fff1f0;border-radius:10px;margin-bottom:1rem}.button,button{font:inherit;font-weight:700;padding:.65rem .85rem;border-radius:9px;border:0;background:#1d2939;color:white;text-decoration:none;cursor:pointer}.secondary{background:transparent;color:inherit;border:1px solid #d0d5dd}.danger{background:#b42318}@media(max-width:800px){.page-heading,.evidence-list article,.form-grid,.inline-form{display:grid}.action-form{min-width:0;max-width:none}}
</style>
